[User Model] Xamarin support
OneSignal/OneSignal-DotNet-SDK pull request #46
Opened 2023-02-27 20:45 UTC by brismithers

* Update platform-specific libraries to use `Xamarin.Legacy.Sdk`, which allows them to target both .NET and Xamarin platforms.
* Update nuspec to support all 4 platforms.

2023-02-27 21:45 UTC, jkasten2 requested changes

2023-02-27 21:45 UTC, jkasten2 commented on OneSignalSDK.DotNet.nuspec
> +            <group targetFramework="monoandroid12.0">
The OneSignal-Android-SDK has support back to Android 4.1. Shouldn't this be `MonoAndroid4.1` instead? See our [OneSignalSDK.Xamarin.nuspec](https://github.com/OneSignal/OneSignal-Xamarin-SDK/blob/main/OneSignalSDK.Xamarin.nuspec#L21).

2023-02-27 21:45 UTC, jkasten2 commented on OneSignalSDK.DotNet.nuspec
> +            <group targetFramework="xamarin.ios10">
In my testing before `ios10` doesn't limit the iOS, so would recommend just using `Xamarin.iOS`. See:
https://github.com/OneSignal/OneSignal-Xamarin-SDK/blob/main/OneSignalSDK.Xamarin.nuspec#LL36C36-L36C47

2023-02-27 21:45 UTC, jkasten2 commented on OneSignalSDK.DotNet.nuspec
> +        <!--net6.0-android31-->
Comment should be `net6.0-android21.0`

2023-02-27 23:02 UTC, brismithers commented on OneSignalSDK.DotNet.nuspec
> +            <group targetFramework="monoandroid12.0">
Package Xamarin.Kotlin.StdLib.Jdk8 1.8.0.1 requires Android v12 / API 31.  So we are forced to use that as our target level.  Though this is only a target compilation level, this will run all the way down to Android 5.0 / API 21, we are restricted by `androidx.security` requiring that at runtime.

2023-02-27 23:04 UTC, brismithers commented on OneSignalSDK.DotNet.nuspec
> +            <group targetFramework="xamarin.ios10">
Similar to Android, I could not go lower than ios10.  The nuspec is a reflection of what we compiled against.  This means that users can build against ios10 or higher.  This will run on levels lower than iOS, though I didn't test how low it will go.

2023-02-28 00:06 UTC, jkasten2 commented on OneSignalSDK.DotNet.nuspec
> +            <group targetFramework="xamarin.ios10">
Ya tried 9.0 / 90 in the past but it created issues. I tried to get Xamarin to update their docs but my PR was never merged:
https://github.com/MicrosoftDocs/xamarin-docs/pull/3447
(most likely since Xamarin is basically deprecated)

2023-02-28 00:07 UTC, jkasten2 commented on OneSignalSDK.DotNet.nuspec
> +            <group targetFramework="monoandroid12.0">
ah ok, this is only a target framework, so the app developer just need to target Android v12 / API 31 (which is required for the Google Play Store now anyway)

2023-02-28 00:09 UTC, jkasten2 approved these changes

2023-02-28 14:56 UTC, merged